# Generated by Django 5.0.1 on 2024-03-06 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurant_App', '0003_alter_food_item_food_item_avaliblity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order_address_city', models.CharField(max_length=200)),
                ('order_address', models.CharField(max_length=300)),
                ('order_address_landmark', models.CharField(max_length=300)),
                ('order_address_instructions', models.CharField(max_length=300)),
                ('order_status', models.CharField(default='Pending', max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_item_qty', models.IntegerField()),
                ('cart_item_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cart_item_instructions', models.CharField(max_length=250)),
                ('food_item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant_App.food_item')),
                ('order_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer_App.order')),
            ],
        ),
    ]
