# Generated by Django 5.0.1 on 2024-03-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_App', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
