# Generated by Django 5.0.1 on 2024-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Type',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_type', models.CharField(choices=[('veg', 'veg'), ('non veg', 'non veg')], max_length=30)),
            ],
        ),
    ]
