# Generated by Django 5.0.1 on 2024-02-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_type',
            name='food_type',
            field=models.CharField(max_length=30),
        ),
    ]
