# Generated by Django 5.0.1 on 2024-02-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_alter_food_type_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Category',
            fields=[
                ('food_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_cat', models.CharField(max_length=30)),
                ('food_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.food_type')),
            ],
        ),
    ]
