# Generated by Django 5.0.1 on 2024-02-11 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_App', '0003_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rest_id', models.AutoField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=50)),
                ('rest_owner_name', models.CharField(max_length=50)),
                ('rest_email', models.CharField(max_length=50)),
                ('rest_pass', models.CharField(max_length=50)),
                ('rest_logo_img', models.ImageField(upload_to='')),
                ('rest_banner_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Item',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_item_name', models.CharField(max_length=50)),
                ('food_item_desc', models.CharField(max_length=150)),
                ('food_item_price', models.FloatField()),
                ('food_item_avaliblity', models.BooleanField()),
                ('food_img', models.ImageField(upload_to='')),
                ('food_cat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.food_category')),
                ('rest_fk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant_App.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_country', models.CharField(max_length=50)),
                ('branch_city', models.CharField(max_length=50)),
                ('branch_locality', models.CharField(max_length=50)),
                ('rest_fk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant_App.restaurant')),
            ],
        ),
    ]
