# Generated by Django 5.0.1 on 2024-02-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item',
            name='food_item_discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='food_item',
            name='food_img',
            field=models.ImageField(upload_to='Food_Item_Img'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_banner_img',
            field=models.ImageField(upload_to='Restaurant_Banner_Img'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_logo_img',
            field=models.ImageField(upload_to='Restaurant_Logo_Img'),
        ),
    ]
