# Generated by Django 5.0.1 on 2024-03-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_App', '0003_alter_food_item_food_item_avaliblity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Timings',
            fields=[
                ('rest_timing_id', models.AutoField(primary_key=True, serialize=False)),
                ('open_timings', models.TimeField()),
                ('closing_timings', models.TimeField()),
                ('rest_fk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant_App.restaurant')),
            ],
        ),
    ]
